### ISSUE TITLE
Array indexed values need some form of length limit to prevent attack

### ISSUE THREAD

**Issue by hdm** [monoculum/formam#31]
The code to expand a slice based on an array index ends up calling `reflect.MakeSlice` with a user-controlled length value:
https://github.com/monoculum/formam/blob/master/formam.go#L570

This could be abused by a malicious user to force large memory allocations in a Go web application.

A workaround could be to provide a default length limit (16k or similar) in the DecoderOptions and allow the user to override this.

**Comment by arp242** [comment]
Good catch; thanks! I created a patch: #32

**Comment by emilgpa** [comment]
@hdm Thank you very much for catching it! And thank you @arp242 for the PR!

**Comment by hdm** [comment]
Thanks for the patch!

**Comment by arp242** [comment]
I put out v3.4.0 which includes this fix.
