### ISSUE TITLE
Missmatching major version and semantic import version (SIV)

### ISSUE THREAD

**Issue by D1CED** [monoculum/formam#47]
Currently this module shows up on go.dev as having no version released https://pkg.go.dev/github.com/monoculum/formam.
This is because there is no release where the major version matches the import version.

The only change needed is to to add the suffix v3 to the module name declared in go.mod.

    module github.com/monoculum/formam/v3

Of course a new minor release would be necessary too.

An effect this will have is that from now on people would need to use SIV when importing your module.

Cheers.

**Comment by emilgpa** [comment]
I hope I can do that these days. Thank you.

**Comment by D1CED** [comment]
Hi, thanks for merging #48. I'll close this when a version has been tagged and is recognized by pkg.go.dev just to verify that this worked properly.

Have a great weekend.

**Comment by emilgpa** [comment]
Great. Thanks you, @D1CED. Have a great weekend too.
