### ISSUE TITLE
Any plans to include custom type marshalling, much like gorilla schema's RegisterConverter?

### ISSUE THREAD

**Issue by joeybloggs** [monoculum/formam#5]
First off, like the library.

Just wondering if there were any plans to implement registering of custom types?

TextMarshler and Unmarshler is great, but when the objects are not under your control, such as bson.ObjectId from the mgo package; can't implement/add TextMarshler and Unmarshler support.

**Comment by dashaus** [comment]
Not plans to include it but I put this as a next feature!
