### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by markbates** [monoculum/formam#9]
Hi @monoculum I'm considering incorporating this library into https://github.com/gobuffalo/buffalo/issues/335, but before I do that, I have to ask if this project is still maintained. If it is not, are you OK if I fork it and maintain a fork for the Buffalo project?

**Comment by dashaus** [comment]
If you want, you can fork it. No problem. This project is still maintained but now I'm busy making my portfolio, but in a relative short period time I will return to it (I have some ideas to implement to it).

**Comment by markbates** [comment]
Awesome. As long as it's still maintained, I'm happy. I'd rather not fork it, but happy to help when I come across stuff. Thanks.
